[tool.poetry]
name = "magic-eraser"
version = "0.1.0"
description = ""
authors = ["Parth Rathod <rathodparth02@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.0"
torchvision = "^0.18.0"
opencv-python = "^4.9.0.80"
matplotlib = "^3.9.0"
pillow-heif = "^0.16.0"
scikit-learn = "^1.5.2"
onnxruntime = "^1.20.0"
pydantic = "^2.10.4"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.2.1"
pdoc = "^15.0.1"

[tool.poetry.scripts]
generate-docs = "scripts.generate_docs:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
