[tool.poetry]
name = "magic-eraser"
version = "0.1.0.dev13"
description = ""
authors = ["Parth Rathod <rathodparth02@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.0"
torchvision = "^0.18.0"
opencv-python = "^4.9.0.80"
matplotlib = "^3.9.0"
pillow-heif = "^0.16.0"
scikit-learn = "^1.5.2"
onnxruntime = "^1.20.0"
pydantic = "^2.10.4"
diffusers = {extras = ["torch"], version = "^0.32.0"}
transformers = "^4.48.0"
python-doctr = {extras = ["torch"], version = "^0.11.0"}
scipy = "^1.15.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.2.1"
pdoc = "^15.0.1"
pytest-cov = "^6.0.0"
gdown = "^5.2.0"

[tool.poetry.scripts]
generate-docs = "scripts.generate_docs:main"
test-coverage-local = "run_coverage_tests:local_coverage"
terminal-coverage = "run_coverage_tests:terminal_coverage"
download-weights = "scripts.download_model_weights:download_weights"

[tool.pytest.ini_options]
addopts = "-v --show-capture=stdout --cov=magic_eraser --ignore=tests/inpainting/test_runwayml.py"
testpaths = ["tests/"]

[tool.coverage.report]
omit = [
        # plot.py is just use for debugging
        "magic_eraser/utils/plot.py",

        # Base Class for all inpainting models, not used directly
        "magic_eraser/inpainting/base.py",

        # Base Class for all segmentation models, not used directly
        "magic_eraser/segmentation/base.py",

        # We are not testing runwayml model since gdown library is not able to download model weights from google drive. 
        # Hence we are skipping and not reporting coverage for it.
        "magic_eraser/inpainting/models/runwayml/*"
]

skip_empty = true
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
