[tool.poetry]
name = "magic-eraser"
version = "0.1.0.dev8"
description = ""
authors = ["Parth Rathod <rathodparth02@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.3.0"
torchvision = "^0.18.0"
opencv-python = "^4.9.0.80"
matplotlib = "^3.9.0"
pillow-heif = "^0.16.0"
scikit-learn = "^1.5.2"
onnxruntime = "^1.20.0"
pydantic = "^2.10.4"
diffusers = {extras = ["torch"], version = "^0.32.0"}
transformers = "^4.48.0"
python-doctr = {extras = ["torch"], version = "^0.11.0"}
scipy = "^1.15.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.2.1"
pdoc = "^15.0.1"
pytest-cov = "^6.0.0"

[tool.poetry.scripts]
generate-docs = "scripts.generate_docs:main"
test-coverage-local = "run_coverage_tests:local_coverage"
terminal-coverage = "run_coverage_tests:terminal_coverage"

[tool.coverage.run]
omit = [
        "*/__init__.py",

        # plot.py is just use for debugging
        "magic_eraser/utils/plot.py"
        ]

[tool.coverage.report]
exclude_also = [
        "if __name__ == .__main__.:",
        "@abstractmethod",
        "def __str__(self):"
        ]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
