name: Bump Pyproject Version

on:
    pull_request:
        types:
            - closed
        branches:
            - "dev"

permissions:
    contents: write

jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit

    bump_version:
        if: github.event.pull_request.merged == true
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.BOT_PAT }}

            - name: Bump Version Script
              uses: ParthDevWorks/development-actions/actions/bump-pyproject-version@main
              with:
                  branch: "dev"
                  token: ${{ secrets.BOT_PAT }}
